### ISSUE TITLE
Add instructions to README for Wordpress import

### ISSUE THREAD

**Issue by danielskatz** [USRSE/blog#8]
How would I suggest importing from https://danielskatzblog.wordpress.com ?

And if I wanted to add a label to some posts there and only import those (let's call it RSE), how would that change things?

**Comment by cosden** [comment]
I haven't done it but take a look at the instructions in the README, and @vsoch has talked about setting up a filter.

**Comment by danielskatz** [comment]
yes, I read the README, but it doesn't answer my questions.  I see that wordpress provides a sitemap.xml - https://danielskatzblog.wordpress.com/sitemap.xml   Is this what I would add?  Or would it be http://danielskatzblog.wordpress.com/feed/ ?  Or  http://danielskatzblog.wordpress.com/feed.xml ?

And how would I express that I just wanted articles with a specific label?  I was hoping that wordpress would be a common enough platform that someone might be able to provide more specific instructions.

**Comment by vsoch** [comment]
hey @danielskatz your WordPress blog has a main feed, it's always at: https://danielskatzblog.wordpress.com/feed/ so you would add that as the link to include all posts. It would be more fine tuned to create a category on your site, and then use that feed instead. If you have a category, I believe you can just do:

https://danielskatzblog.wordpress.com/<category>/<feed>/

I'd be happy to PR with wordpress instructions! I haven't used it since https://gogglesoptional.com/ but I bet it hasn't changed much. :) 

Do you want to try creating a category and seeing if the feed link is there (and if not, I can look into how to turn it on).

**Comment by danielskatz** [comment]
@vsoch - I'm very confused by the middle URL in your comment above - did something go wrong between typing and posting?

**Comment by vsoch** [comment]
Oh, it's rendering weird in the comment (I put braces) let me fix it up.

**Comment by vsoch** [comment]
There we go! The idea is that if you create a category named "rse," then the feed would be at

`https://danielskatzblog.wordpress.com/rse/feed/`

Back in the day the user (used to) have to "turn on" the category feeds, but it may work out of the box now. if it doesn't I can find instructions for how to still activate.

**Comment by vsoch** [comment]
Actually here is a *much* better source of information https://wordpress.org/support/article/wordpress-feeds/#categories-and-tags

**Comment by vsoch** [comment]
Closed with #13
